# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            IHS Makers
paginate:         1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
